<?xml version="1.0" encoding="UTF-8"?>
<!-- COS2023 land-cover style for GeoServer, same classes and colours as cos2023.sld.
     One Recode on COS23_n4_C instead of one Rule per class: GeoServer evaluates every Rule
     filter per feature, MapServer stops at the first matching CLASS. -->
<StyledLayerDescriptor version="1.0.0"
    xmlns="http://www.opengis.net/sld" xmlns:ogc="http://www.opengis.net/ogc">
  <NamedLayer><Name>cos2023</Name><UserStyle>
    <Title>COS2023 - Carta de Uso e Ocupacao do Solo (DGT)</Title>
    <FeatureTypeStyle>
    <Rule>
      <PolygonSymbolizer><Fill>
        <CssParameter name="fill">
          <ogc:Function name="Recode">
            <ogc:PropertyName>COS23_n4_C</ogc:PropertyName>
            <ogc:Literal>1.1.1.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.1.1.2</ogc:Literal><ogc:Literal>#e60014</ogc:Literal>
            <ogc:Literal>1.1.2.1</ogc:Literal><ogc:Literal>#ff0000</ogc:Literal>
            <ogc:Literal>1.1.2.2</ogc:Literal><ogc:Literal>#ff0032</ogc:Literal>
            <ogc:Literal>1.1.3.1</ogc:Literal><ogc:Literal>#ff0050</ogc:Literal>
            <ogc:Literal>1.1.3.2</ogc:Literal><ogc:Literal>#ff006e</ogc:Literal>
            <ogc:Literal>1.2.1.1</ogc:Literal><ogc:Literal>#cc4df2</ogc:Literal>
            <ogc:Literal>1.2.2.1</ogc:Literal><ogc:Literal>#cc4dd2</ogc:Literal>
            <ogc:Literal>1.2.3.1</ogc:Literal><ogc:Literal>#cc4da0</ogc:Literal>
            <ogc:Literal>1.3.1.1</ogc:Literal><ogc:Literal>#cc4d78</ogc:Literal>
            <ogc:Literal>1.3.1.2</ogc:Literal><ogc:Literal>#cc4d5a</ogc:Literal>
            <ogc:Literal>1.3.2.1</ogc:Literal><ogc:Literal>#cc4d46</ogc:Literal>
            <ogc:Literal>1.3.2.2</ogc:Literal><ogc:Literal>#cc4d28</ogc:Literal>
            <ogc:Literal>1.4.1.1</ogc:Literal><ogc:Literal>#cc0000</ogc:Literal>
            <ogc:Literal>1.4.1.2</ogc:Literal><ogc:Literal>#9a0000</ogc:Literal>
            <ogc:Literal>1.4.2.1</ogc:Literal><ogc:Literal>#e6cccc</ogc:Literal>
            <ogc:Literal>1.4.2.2</ogc:Literal><ogc:Literal>#e6b4cc</ogc:Literal>
            <ogc:Literal>1.4.2.3</ogc:Literal><ogc:Literal>#e696cc</ogc:Literal>
            <ogc:Literal>1.4.3.1</ogc:Literal><ogc:Literal>#e6cce6</ogc:Literal>
            <ogc:Literal>1.4.3.2</ogc:Literal><ogc:Literal>#d2cce6</ogc:Literal>
            <ogc:Literal>1.5.1.1</ogc:Literal><ogc:Literal>#a600cc</ogc:Literal>
            <ogc:Literal>1.5.1.2</ogc:Literal><ogc:Literal>#6e00cc</ogc:Literal>
            <ogc:Literal>1.5.2.1</ogc:Literal><ogc:Literal>#a64d00</ogc:Literal>
            <ogc:Literal>1.5.2.2</ogc:Literal><ogc:Literal>#a67400</ogc:Literal>
            <ogc:Literal>1.5.3.1</ogc:Literal><ogc:Literal>#ff4dff</ogc:Literal>
            <ogc:Literal>1.6.1.1</ogc:Literal><ogc:Literal>#ffe6ff</ogc:Literal>
            <ogc:Literal>1.6.1.2</ogc:Literal><ogc:Literal>#ffd2ff</ogc:Literal>
            <ogc:Literal>1.6.2.1</ogc:Literal><ogc:Literal>#ffb4ff</ogc:Literal>
            <ogc:Literal>1.6.2.2</ogc:Literal><ogc:Literal>#ff8cff</ogc:Literal>
            <ogc:Literal>1.6.3.1</ogc:Literal><ogc:Literal>#e664ff</ogc:Literal>
            <ogc:Literal>1.6.4.1</ogc:Literal><ogc:Literal>#be64ff</ogc:Literal>
            <ogc:Literal>1.6.5.1</ogc:Literal><ogc:Literal>#a064ff</ogc:Literal>
            <ogc:Literal>1.7.1.1</ogc:Literal><ogc:Literal>#ffa6ff</ogc:Literal>
            <ogc:Literal>2.1.1.1</ogc:Literal><ogc:Literal>#ffff00</ogc:Literal>
            <ogc:Literal>2.1.1.2</ogc:Literal><ogc:Literal>#e6e600</ogc:Literal>
            <ogc:Literal>2.2.1.1</ogc:Literal><ogc:Literal>#e68000</ogc:Literal>
            <ogc:Literal>2.2.2.1</ogc:Literal><ogc:Literal>#f2a64d</ogc:Literal>
            <ogc:Literal>2.2.3.1</ogc:Literal><ogc:Literal>#e6a600</ogc:Literal>
            <ogc:Literal>2.3.1.1</ogc:Literal><ogc:Literal>#ffe6a6</ogc:Literal>
            <ogc:Literal>2.3.1.2</ogc:Literal><ogc:Literal>#fff0a6</ogc:Literal>
            <ogc:Literal>2.3.1.3</ogc:Literal><ogc:Literal>#fffaa6</ogc:Literal>
            <ogc:Literal>2.3.2.1</ogc:Literal><ogc:Literal>#ffe64d</ogc:Literal>
            <ogc:Literal>2.3.3.1</ogc:Literal><ogc:Literal>#e6cc4d</ogc:Literal>
            <ogc:Literal>2.4.1.1</ogc:Literal><ogc:Literal>#e6cc82</ogc:Literal>
            <ogc:Literal>3.1.1.1</ogc:Literal><ogc:Literal>#ffff4d</ogc:Literal>
            <ogc:Literal>3.1.2.1</ogc:Literal><ogc:Literal>#ccf24d</ogc:Literal>
            <ogc:Literal>4.1.1.1</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.1.1.2</ogc:Literal><ogc:Literal>#dccca6</ogc:Literal>
            <ogc:Literal>4.1.1.3</ogc:Literal><ogc:Literal>#c8cca6</ogc:Literal>
            <ogc:Literal>4.1.1.4</ogc:Literal><ogc:Literal>#b4cca6</ogc:Literal>
            <ogc:Literal>4.1.1.5</ogc:Literal><ogc:Literal>#a0d7a6</ogc:Literal>
            <ogc:Literal>4.1.1.6</ogc:Literal><ogc:Literal>#a0e6a6</ogc:Literal>
            <ogc:Literal>4.1.1.7</ogc:Literal><ogc:Literal>#a0ffa6</ogc:Literal>
            <ogc:Literal>5.1.1.1</ogc:Literal><ogc:Literal>#80ff00</ogc:Literal>
            <ogc:Literal>5.1.1.2</ogc:Literal><ogc:Literal>#80eb00</ogc:Literal>
            <ogc:Literal>5.1.1.3</ogc:Literal><ogc:Literal>#80d700</ogc:Literal>
            <ogc:Literal>5.1.1.4</ogc:Literal><ogc:Literal>#80c800</ogc:Literal>
            <ogc:Literal>5.1.1.5</ogc:Literal><ogc:Literal>#80b400</ogc:Literal>
            <ogc:Literal>5.1.1.6</ogc:Literal><ogc:Literal>#80a000</ogc:Literal>
            <ogc:Literal>5.1.1.7</ogc:Literal><ogc:Literal>#808c00</ogc:Literal>
            <ogc:Literal>5.1.2.1</ogc:Literal><ogc:Literal>#00a600</ogc:Literal>
            <ogc:Literal>5.1.2.2</ogc:Literal><ogc:Literal>#008c00</ogc:Literal>
            <ogc:Literal>5.1.2.3</ogc:Literal><ogc:Literal>#007800</ogc:Literal>
            <ogc:Literal>6.1.1.1</ogc:Literal><ogc:Literal>#a6ff80</ogc:Literal>
            <ogc:Literal>7.1.1.1</ogc:Literal><ogc:Literal>#e6e6e6</ogc:Literal>
            <ogc:Literal>7.1.1.2</ogc:Literal><ogc:Literal>#e6e6d7</ogc:Literal>
            <ogc:Literal>7.1.2.1</ogc:Literal><ogc:Literal>#cccccc</ogc:Literal>
            <ogc:Literal>7.1.3.1</ogc:Literal><ogc:Literal>#ccffcc</ogc:Literal>
            <ogc:Literal>8.1.1.1</ogc:Literal><ogc:Literal>#a6a6ff</ogc:Literal>
            <ogc:Literal>8.1.2.1</ogc:Literal><ogc:Literal>#ccccff</ogc:Literal>
            <ogc:Literal>8.1.2.2</ogc:Literal><ogc:Literal>#a6a6e6</ogc:Literal>
            <ogc:Literal>9.1.1.1</ogc:Literal><ogc:Literal>#00ccf2</ogc:Literal>
            <ogc:Literal>9.1.1.2</ogc:Literal><ogc:Literal>#00f2f2</ogc:Literal>
            <ogc:Literal>9.1.2.1</ogc:Literal><ogc:Literal>#80f2e6</ogc:Literal>
            <ogc:Literal>9.1.2.2</ogc:Literal><ogc:Literal>#80dee6</ogc:Literal>
            <ogc:Literal>9.1.2.3</ogc:Literal><ogc:Literal>#80c8e6</ogc:Literal>
            <ogc:Literal>9.1.2.4</ogc:Literal><ogc:Literal>#80b4e6</ogc:Literal>
            <ogc:Literal>9.1.2.5</ogc:Literal><ogc:Literal>#80a0e6</ogc:Literal>
            <ogc:Literal>9.2.1.1</ogc:Literal><ogc:Literal>#e6e6ff</ogc:Literal>
            <ogc:Literal>9.3.1.1</ogc:Literal><ogc:Literal>#e6ffff</ogc:Literal>
            <ogc:Literal>9.3.2.1</ogc:Literal><ogc:Literal>#00ffa6</ogc:Literal>
            <ogc:Literal>9.3.3.1</ogc:Literal><ogc:Literal>#a6ffe6</ogc:Literal>
            <ogc:Literal>9.3.4.1</ogc:Literal><ogc:Literal>#e6f2ff</ogc:Literal>
            <ogc:Literal>1.2.1.2</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.3.2.3</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.3.2.4</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.3.3.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.3.4.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.4.1.3</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.4.4.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.4.4.2</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.4.5.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.4.5.2</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.4.6.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.5.2.3</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.5.3.2</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.5.4.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.7.1.2</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>1.8.1.1</ogc:Literal><ogc:Literal>#e6004d</ogc:Literal>
            <ogc:Literal>4.1.2.1</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.1.2.2</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.2.1.1</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.2.1.2</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.2.1.3</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.2.1.4</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.2.2.1</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>4.2.2.2</ogc:Literal><ogc:Literal>#f2cca6</ogc:Literal>
            <ogc:Literal>5.1.1.8</ogc:Literal><ogc:Literal>#80ff00</ogc:Literal>
          </ogc:Function>
        </CssParameter>
      </Fill></PolygonSymbolizer>
    </Rule>
  </FeatureTypeStyle>
  </UserStyle></NamedLayer>
</StyledLayerDescriptor>
